'use strict';
const {products,categories,cleanCart,totals,filterProducts}=Comercio;
const $=s=>document.querySelector(s);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=c=>new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'}).format(c/100);
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem('comercio-'+key))??fallback}catch{return fallback}};
const write=(key,value)=>{try{localStorage.setItem('comercio-'+key,JSON.stringify(value));return true}catch{return false}};
let cart=cleanCart(read('cart',{}));let favorites=read('favorites',[]);if(!Array.isArray(favorites))favorites=[];favorites=favorites.filter(id=>products.some(p=>p.id===id));
let orders=read('orders',[]);if(!Array.isArray(orders))orders=[];orders=orders.filter(o=>o&&typeof o.id==='string'&&Array.isArray(o.items)&&Number.isFinite(o.total));
let savedLocation=read('location',{});if(!savedLocation||typeof savedLocation!=='object')savedLocation={};
let state={query:'',category:'Todos',offers:false,favoritesOnly:false,sort:'featured'},coupon='',delivery=savedLocation.method==='pickup'?'pickup':'delivery';
const paths={search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',heart:'<path d="M20.8 4.8a5.5 5.5 0 0 0-7.8 0L12 5.9l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.4a5.5 5.5 0 0 0 0-7.8Z"/>',bag:'<path d="M5 7h14l1 14H4L5 7Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/>',user:'<circle cx="12" cy="7" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',truck:'<path d="M2 5h12v12H2zM14 9h4l4 5v3h-8"/><circle cx="6" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>',leaf:'<path d="M20 3C7 1 1 10 7 17s16 0 13-14Z"/><path d="m3 22 13-13"/>',tag:'<path d="m3 12 9 9 10-10V2H13L3 12Z"/><circle cx="17" cy="7" r="1"/>',shield:'<path d="M12 2 3 6v6c0 6 9 10 9 10s9-4 9-10V6l-9-4Z"/><path d="m8 12 3 3 5-6"/>',home:'<path d="m2 10 10-8 10 8M5 9v12h14V9M10 21v-7h4v7"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${paths[n]||paths.bag}</svg>`;
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
let artSequence=0;
function art(type,label=''){
const shapes={
tomato:'<ellipse cx="101" cy="144" rx="68" ry="10" fill="#bbc49f" opacity=".35"/><circle cx="83" cy="106" r="37" fill="url(#red)"/><circle cx="130" cy="113" r="30" fill="url(#red)"/><path d="m81 76-11-17 17 6 8-14 3 19 17-2-19 13Z" fill="#3c7839"/><path d="m128 87-13-10 14 3 9-13 1 16 12 2-18 9Z" fill="#3c7839"/><ellipse cx="69" cy="97" rx="7" ry="12" fill="white" opacity=".18"/>',
avocado:'<ellipse cx="98" cy="146" rx="67" ry="8" fill="#9da986" opacity=".3"/><path d="M60 34c-10 0-23 22-29 48-17 57 42 77 64 43 17-27-5-61-18-80-4-7-10-11-17-11Z" fill="#426942"/><path d="M119 32c-17 0-27 24-40 54-17 40 10 61 38 62 29 1 57-24 38-61-14-26-18-55-36-55Z" fill="#6a8c47"/><path d="M118 42c-12 0-23 30-33 49-16 31 7 48 32 48s46-19 32-47c-9-18-19-50-31-50Z" fill="#d8dd83"/><circle cx="117" cy="109" r="23" fill="url(#brown)"/><ellipse cx="111" cy="100" rx="8" ry="6" fill="#d5a078" opacity=".4"/>',
bread:'<ellipse cx="102" cy="143" rx="78" ry="10" fill="#b7a989" opacity=".25"/><g transform="rotate(-16 100 90)"><rect x="22" y="52" width="154" height="72" rx="35" fill="url(#gold)"/><path d="m53 67-7 35m42-38-9 43m43-42-9 39m39-34-7 29" stroke="#ffe0a0" stroke-width="12" stroke-linecap="round"/><path d="m34 115 125 1" stroke="#b27137" stroke-width="3" opacity=".3"/></g>',
banana:'<ellipse cx="105" cy="143" rx="67" ry="9" fill="#b5ab79" opacity=".25"/><path d="M44 40c-4 84 75 109 119 38-18 91-123 88-135 17-3-20 1-41 8-59Z" fill="#e8b941"/><path d="M59 40c-1 83 68 103 114 25-15 99-107 112-127 25-5-16-3-40 3-53Z" fill="#f4d65e"/><path d="M74 37c7 67 56 65 91 22-6 74-80 100-97 31-5-19-6-36-2-57Z" fill="#ffe685"/><path d="m40 42 29-7" stroke="#6b603e" stroke-width="10"/><path d="m168 67 4-6" stroke="#79603b" stroke-width="5"/>',
apple:'<ellipse cx="102" cy="145" rx="66" ry="8" fill="#ac9b7c" opacity=".25"/><path d="M97 69c-32-27-72-1-61 38 14 42 37 44 59 31 22 14 49 4 58-31 12-42-28-64-56-38Z" fill="url(#red)"/><path d="m96 69 4-29" stroke="#664d33" stroke-width="6"/><path d="M102 48c18-24 35-8 32-4-4 6-18 13-32 4Z" fill="#568348"/><ellipse cx="61" cy="92" rx="8" ry="15" fill="white" opacity=".17"/>',
carrot:'<g transform="rotate(30 100 90)"><path d="M84 57c-23-49-4-51 6-10-5-55 15-56 10-2 16-55 32-45 10 12Z" fill="#518446"/><path d="M70 57c-3 45 23 100 27 100 6 0 31-56 31-100-15-9-39-9-58 0Z" fill="url(#orange)"/><path d="m72 81 17 2m22 15 10-2m-39 24 13 1" stroke="#c5702e" stroke-width="3"/></g>',
eggs:'<path d="M24 99h153l-12 47H35Z" fill="#bba98a"/><path d="m26 104 12 34h125l10-34" fill="#cbbb9c"/><g fill="url(#egg)"><ellipse cx="56" cy="82" rx="22" ry="31"/><ellipse cx="100" cy="78" rx="22" ry="33"/><ellipse cx="144" cy="82" rx="22" ry="31"/></g><path d="m26 107 148 0" stroke="#a59171" stroke-width="5"/>',
cheese:'<ellipse cx="102" cy="145" rx="66" ry="8" fill="#b5a779" opacity=".25"/><path d="m35 114 43-66 87 52-22 38Z" fill="#f2d575"/><path d="m35 114 107 24 23-38-79-5Z" fill="#ebbf50"/><path d="m35 114 107 24v-36L78 48Z" fill="#ffdf81"/><g fill="#ddae4d"><ellipse cx="65" cy="104" rx="8" ry="7"/><ellipse cx="109" cy="111" rx="9" ry="8"/><ellipse cx="86" cy="87" rx="6" ry="7"/></g>',
croissant:'<ellipse cx="103" cy="140" rx="74" ry="10" fill="#b5a582" opacity=".25"/><path d="M30 101c2-59 112-81 147-15l-23 35-33-29-42 8-28 29Z" fill="url(#gold)"/><path d="m57 64 19 38m9-48 12 44m26-39-7 38m34-24-20 28" stroke="#b57c3e" stroke-width="3" opacity=".6"/><path d="m33 99 18 30 27-29m46-8 30 29 22-36" stroke="#f4c77b" stroke-width="8" fill="none"/>',
milk:'<path d="m70 35 9-16h44l10 16v113H70Z" fill="#fcfcf1" stroke="#d7ded2"/><path d="m70 35 11-16v116l-11 13Z" fill="#d8e4d7"/><path d="M80 69h53v47H80Z" fill="#679494"/><path d="m81 35 42-16 10 16Z" fill="#e6ecdf"/><rect x="112" y="23" width="14" height="8" rx="3" fill="#528885"/><text x="107" y="89" fill="white" font-size="9" text-anchor="middle" font-family="sans-serif" font-weight="bold">COMERCIO</text><text x="107" y="104" fill="white" font-size="10" text-anchor="middle" font-family="serif">LECHE</text><path d="m89 127 32 0" stroke="#c5d4c3" stroke-width="2"/>',
coffee:'<path d="M61 29h81l7 114H55Z" fill="#d8b787"/><path d="m61 29 81 0m-85 108 89 0" stroke="#a88658" stroke-width="5"/><path d="M60 60h83v56H58Z" fill="#3e5844"/><text x="100" y="79" text-anchor="middle" fill="#f6e7c8" font-size="8" font-family="sans-serif">COMERCIO</text><text x="100" y="99" text-anchor="middle" fill="#f6e7c8" font-size="17" font-family="serif">Café</text><ellipse cx="99" cy="121" rx="7" ry="4" fill="#775032"/><path d="m59 34 81 0" stroke="#edd1a0"/>',
rice:'<path d="M60 27h81l7 117H53Z" fill="#f0e8cc"/><path d="M60 27h81v21H60Z" fill="#537c4e"/><rect x="65" y="62" width="71" height="48" rx="3" fill="#faf9e9"/><text x="100" y="79" text-anchor="middle" fill="#537c4e" font-size="8" font-family="sans-serif">COMERCIO</text><text x="100" y="98" text-anchor="middle" fill="#537c4e" font-size="16" font-family="serif">Arroz</text><path d="m64 121 73 0" stroke="#cdbf98" stroke-width="8"/><path d="m69 121 12 0m13 0 12 0m13 0 10 0" stroke="#faf7e4" stroke-width="3"/>',
pasta:'<path d="M62 25h78l7 121H55Z" fill="#e4c88b"/><path d="M62 25h78v24H62Z" fill="#a95035"/><rect x="64" y="65" width="73" height="49" rx="3" fill="#f6df9f"/><g stroke="#e3b157" stroke-width="7"><path d="m73 70 18 18m5-19 18 18m6-15 12 13m-58 8 13 14m11-15 18 17m6-13 10 10"/></g><text x="100" y="60" text-anchor="middle" fill="#754b2b" font-size="10" font-family="serif">PENNE</text>',
juice:'<path d="m70 35 9-16h44l10 16v113H70Z" fill="#f2bb58"/><path d="m70 35 9-16v113l-9 16Z" fill="#d99e3d"/><path d="m79 35 44-16 10 16Z" fill="#f9db93"/><rect x="114" y="22" width="12" height="9" rx="3" fill="#efefe0"/><rect x="82" y="62" width="51" height="57" fill="#f7ecc8"/><text x="107" y="78" text-anchor="middle" fill="#41734b" font-size="7" font-family="sans-serif">COMERCIO</text><circle cx="106" cy="97" r="15" fill="#f19b37"/><path d="M105 81c2-9 12-10 15-5-5 4-8 6-15 5Z" fill="#5e8550"/><text x="107" y="132" text-anchor="middle" fill="#7d592a" font-size="7">NARANJA</text>',
water:'<rect x="86" y="16" width="30" height="13" rx="3" fill="#54888a"/><path d="M84 30h34v15c0 10 18 13 18 28v65c0 7-6 11-14 11H78c-8 0-14-4-14-11V73c0-15 20-18 20-28Z" fill="#cee1e3" stroke="#a5c8ca"/><path d="m69 70 63 0m-63 61 63 0" stroke="#b1d1d3" stroke-width="5"/><rect x="65" y="86" width="70" height="28" fill="#5d9294"/><text x="100" y="103" text-anchor="middle" fill="white" font-size="12" font-family="serif">Agua</text><path d="m78 50 0 84" stroke="white" opacity=".5" stroke-width="5"/>',
yogurt:'<path d="M56 58h88l-13 90H69Z" fill="#f9f9ef" stroke="#dce3d3"/><path d="m56 60 88 0" stroke="#6d9777" stroke-width="12"/><path d="M61 83h78l-4 45H66Z" fill="#7ca189"/><text x="101" y="99" text-anchor="middle" fill="white" font-size="8" font-family="sans-serif">COMERCIO</text><text x="101" y="117" text-anchor="middle" fill="white" font-size="15" font-family="serif">Yogur</text><ellipse cx="100" cy="51" rx="45" ry="8" fill="#d8e4d1"/>',
soap:'<path d="M86 35h30v15h-30Z" fill="#6c8595"/><path d="M81 22h35v11H81v-11l-17 0v8" stroke="#6c8595" stroke-width="6" fill="none"/><rect x="68" y="47" width="67" height="103" rx="15" fill="#adcad2"/><rect x="70" y="82" width="63" height="42" fill="#f7f7ed"/><text x="102" y="95" text-anchor="middle" fill="#567785" font-size="7" font-family="sans-serif">COMERCIO</text><text x="102" y="111" text-anchor="middle" fill="#567785" font-size="12" font-family="serif">Manos</text><path d="m79 58 0 74" stroke="white" opacity=".3" stroke-width="5"/>',
detergent:'<path d="M85 20h38v16H85Z" fill="#487563"/><path d="M79 36h48c11 0 21 18 21 31v74c0 6-5 10-11 10H66c-7 0-11-5-11-12V63c0-12 15-23 24-27Z" fill="#82ab94"/><path d="M118 47c9 0 19 6 19 20v16h-19Z" fill="#eff4ec"/><path d="M63 90h79v43H63Z" fill="#f7f5e8"/><text x="102" y="105" text-anchor="middle" fill="#4c765f" font-size="7" font-family="sans-serif">COMERCIO</text><text x="102" y="121" text-anchor="middle" fill="#4c765f" font-size="11" font-family="serif">Limpieza</text>'
};
const prefix="art"+(++artSequence)+"-";
return `<svg viewBox="0 0 200 170" ${label?`role="img" aria-label="${escapeHTML(label)}"`:'aria-hidden="true"'}><defs><radialGradient id="red"><stop stop-color="#ef7353"/><stop offset="1" stop-color="#c44432"/></radialGradient><linearGradient id="gold" x2="0" y2="1"><stop stop-color="#eec18a"/><stop offset="1" stop-color="#c89252"/></linearGradient><radialGradient id="brown"><stop stop-color="#9f6943"/><stop offset="1" stop-color="#71432c"/></radialGradient><linearGradient id="orange" x2="1" y2="1"><stop stop-color="#efb04e"/><stop offset="1" stop-color="#df7934"/></linearGradient><linearGradient id="egg"><stop stop-color="#f7ecce"/><stop offset="1" stop-color="#d9bd8e"/></linearGradient></defs>${shapes[type]||shapes.bread}</svg>`.replace(/id="(red|gold|brown|orange|egg)"/g,(_,id)=>`id="${prefix}${id}"`).replace(/url\(#(red|gold|brown|orange|egg)\)/g,(_,id)=>`url(#${prefix}${id})`);
}
function heroArt(){return `<svg viewBox="0 0 560 460" aria-hidden="true"><defs><linearGradient id="bagG" x2=".8" y2="1"><stop stop-color="#e1bd86"/><stop offset="1" stop-color="#c79e66"/></linearGradient></defs><circle cx="300" cy="211" r="177" fill="#dce5cc"/><circle cx="300" cy="211" r="155" fill="none" stroke="#c6d5b6" stroke-dasharray="3 8"/><path d="m463 54 4 11 11 4-11 4-4 11-4-11-11-4 11-4Z" fill="#84a37a"/><ellipse cx="286" cy="407" rx="179" ry="18" fill="#9fae8025"/><g transform="translate(115 79) rotate(-20 90 60)">${art('bread').replace('<svg viewBox="0 0 200 170" aria-hidden="true">','<svg width="235" height="200" viewBox="0 0 200 170">')}</g><g transform="translate(270 90) rotate(15 100 85)">${art('carrot').replace('<svg viewBox="0 0 200 170" aria-hidden="true">','<svg width="180" height="180" viewBox="0 0 200 170">')}</g><path d="M300 201c-90-78-32-95-6-29-34-90 6-125 25-21 16-88 58-80 24 5 59-82 91-28 13 38Z" fill="#66854e"/><path d="M299 202c-13-67-6-92 14-112 12 50 6 79-1 112 8-56 25-72 53-83-5 34-26 65-39 87Z" fill="#8b9c54"/><g transform="translate(72 127)">${art('tomato').replace('<svg viewBox="0 0 200 170" aria-hidden="true">','<svg width="180" height="140" viewBox="0 0 200 170">')}</g><path d="m144 228 272-12-27 181-211 0Z" fill="url(#bagG)"/><path d="m144 228 30 9 22 159-18 1Z" fill="#b78c55"/><path d="m174 237 242-21-17 16-203 13Z" fill="#e7c696"/><path d="M223 239v-35c0-82 111-82 111 0v30" fill="none" stroke="#a97f4d" stroke-width="14"/><path d="M223 239v-35c0-82 111-82 111 0v30" fill="none" stroke="#edd1a6" stroke-width="8"/><text x="287" y="326" text-anchor="middle" fill="#426a48" font-size="34" font-family="Georgia" font-weight="bold" letter-spacing="-1">comercio.</text><text x="285" y="347" text-anchor="middle" fill="#876e4c" font-size="9" font-family="sans-serif" letter-spacing="4">BUENO POR NATURALEZA</text><g transform="translate(326 291) rotate(15 80 70)">${art('avocado').replace('<svg viewBox="0 0 200 170" aria-hidden="true">','<svg width="165" height="145" viewBox="0 0 200 170">')}</g><g transform="translate(44 310) rotate(-10 80 70)">${art('apple').replace('<svg viewBox="0 0 200 170" aria-hidden="true">','<svg width="150" height="128" viewBox="0 0 200 170">')}</g><g transform="translate(392 124) rotate(9)"><rect width="98" height="67" rx="10" fill="#fffdf3"/><text x="49" y="26" text-anchor="middle" fill="#547844" font-size="10" font-family="sans-serif">A TU RITMO</text><text x="49" y="48" text-anchor="middle" fill="#547844" font-size="16" font-family="Georgia" font-style="italic">cada día.</text></g></svg>`;}
$('#heroArt').innerHTML=heroArt();$('#year').textContent=new Date().getFullYear();
function quantity(id,n){return `<div class="quantity"><button data-change="${id}" data-delta="-1" aria-label="Quitar una unidad de ${escapeHTML(products.find(p=>p.id===id).name)}">−</button><span>${n}</span><button data-change="${id}" data-delta="1" aria-label="Agregar una unidad de ${escapeHTML(products.find(p=>p.id===id).name)}" ${n>=products.find(p=>p.id===id).stock?'disabled':''}>+</button></div>`;}
function render(){
 $('#categories').innerHTML=categories.map(c=>`<button class="category ${state.category===c.name?'selected':''}" data-category="${c.name}" aria-pressed="${state.category===c.name}">${art(c.art)}<strong>${c.name}</strong><small>${products.filter(p=>p.category===c.name).length} productos</small></button>`).join('');
 $('#filters').innerHTML=['Todos',...categories.map(c=>c.name)].map(c=>`<button class="filter ${state.category===c?'selected':''}" data-category="${c}" aria-pressed="${state.category===c}">${c}</button>`).join('')+(state.offers?'<button class="filter selected" data-action="offers">Ofertas ✕</button>':'')+(state.favoritesOnly?'<button class="filter selected" data-action="favorites">Favoritos ✕</button>':'');
 const list=filterProducts({...state,favorites});$('#catalogTitle').textContent=state.favoritesOnly?'Tus favoritos':state.offers?'Buenas ofertas para tu día':state.query?'Resultados de búsqueda':state.category==='Todos'?'Favoritos de tu despensa':state.category;
 $('#resultCount').textContent=`${list.length} ${list.length===1?'producto disponible':'productos disponibles'}${state.query?' para «'+state.query+'»':''}`;$('#empty').hidden=!!list.length;
 $('#products').innerHTML=list.map(p=>`<article class="product-card" style="--product-bg:${p.bg}"><div class="product-image"><span class="badge ${p.old?'':'fresh'}">${p.tag}</span><button class="icon-button favorite ${favorites.includes(p.id)?'saved':''}" data-favorite="${p.id}" aria-label="${favorites.includes(p.id)?'Quitar de':'Agregar a'} favoritos: ${p.name}" aria-pressed="${favorites.includes(p.id)}"><span class="icon">${icon('heart')}</span></button>${art(p.art,p.name)}</div><div class="product-body"><span class="product-category">${p.category}</span><h3><button data-detail="${p.id}" style="padding:0;text-align:left">${p.name}</button></h3><span class="product-unit">${p.unit}</span><div class="price-row"><span class="price">${money(p.price)}</span>${p.old&&!cart[p.id]?`<span class="old-price">${money(p.old)}</span>`:''}${cart[p.id]?quantity(p.id,cart[p.id]):`<button class="add-button" data-change="${p.id}" data-delta="1" aria-label="Agregar ${p.name} al carrito">+</button>`}</div></div></article>`).join('');
 const n=Object.values(cart).reduce((s,n)=>s+n,0);$('#cartCount').textContent=n;$('#mobileCount').textContent=n;$('#drawerCount').textContent=`(${n})`;if($('#cartDialog').open)renderCart();
}
let toastTimer;function toast(message){const el=$('#toast');const active=document.querySelector('dialog[open]');if(active){active.append(el);el.classList.add('in-dialog')}else{document.body.append(el);el.classList.remove('in-dialog')}el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),3300);}
function showModal(html){closeDialogs();$('#modalContent').innerHTML=html;$('#modal').showModal();}
function closeDialogs(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());document.body.append($('#toast'));$('#toast').classList.remove('in-dialog','visible');}
function browse(reset=true){if(reset){state={query:'',category:'Todos',offers:false,favoritesOnly:false,sort:'featured'};$('#search').value='';$('#sort').value='featured'}closeDialogs();render();$('#productos').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
function renderCart(){const t=totals(cart,coupon,delivery);const list=products.filter(p=>cart[p.id]);$('#cartItems').innerHTML=list.length?list.map(p=>`<div class="cart-line">${art(p.art)}<div class="cart-line-info"><h3>${p.name}</h3><small>${p.unit} · ${money(p.price)} c/u</small>${quantity(p.id,cart[p.id])}</div><div><strong>${money(p.price*cart[p.id])}</strong><button class="remove" data-remove="${p.id}">Eliminar</button></div></div>`).join(''):'<div class="empty"><span class="icon">'+icon('bag')+'</span><h3>Tu carrito espera algo bueno</h3><p>Agrega productos para comenzar.</p><button class="primary" data-action="catalog">Explorar productos</button></div>';
 $('#cartSummary').innerHTML=list.length?`<div class="muted">${t.subtotal>=3500?'Tu envío de demostración es gratis.':`Agrega ${money(3500-t.subtotal)} para envío demo gratis.`}</div><form class="coupon-form" id="couponForm"><input name="coupon" placeholder="Código de descuento" aria-label="Código de descuento" value="${coupon}" maxlength="30"><button>${coupon?'Cambiar':'Aplicar'}</button></form>${coupon?'<button class="text-button" data-action="removeCoupon">Quitar cupón ✕</button>':''}<div class="summary-row"><span>Subtotal</span><strong>${money(t.subtotal)}</strong></div>${t.discount?`<div class="summary-row"><span>Descuento (10%)</span><strong>−${money(t.discount)}</strong></div>`:''}<div class="summary-row"><span>${delivery==='pickup'?'Retiro en tienda':'Envío estimado'}</span><strong>${t.shipping?money(t.shipping):'Gratis'}</strong></div><div class="summary-row total"><span>Total</span><strong>${money(t.total)}</strong></div><button class="primary wide" data-action="checkout">Continuar mi compra <span>↗</span></button><div class="demo-note">Compra de demostración. No se realizan cobros ni entregas reales.</div>`:'';
}
function checkout(){if(!Object.keys(cart).length)return toast('Agrega un producto antes de continuar.');const t=totals(cart,coupon,delivery);showModal(`<span class="eyebrow">YA CASI ESTÁ</span><h2>Finaliza tu compra</h2><div class="demo-note">Este pedido es de demostración y se guarda solo en este navegador. No cobraremos dinero ni enviaremos productos.</div><form id="checkoutForm" class="form-grid"><label>Nombre completo<input name="name" autocomplete="name" minlength="3" maxlength="80" required></label><label>Correo electrónico<input type="email" name="email" autocomplete="email" maxlength="120" required></label><label>Teléfono<input name="phone" type="tel" autocomplete="tel" pattern="[+0-9 ()-]{8,20}" maxlength="20" placeholder="Ej. 7000 0000" required></label><label>¿Cómo quieres recibir?<select name="method" id="checkoutMethod"><option value="delivery" ${delivery==='delivery'?'selected':''}>Entrega a domicilio (demo)</option><option value="pickup" ${delivery==='pickup'?'selected':''}>Retiro en tienda (demo)</option></select></label><label class="full" id="addressLabel" ${delivery==='pickup'?'hidden':''}>Dirección de entrega<input name="address" autocomplete="street-address" maxlength="200" minlength="8" placeholder="Municipio, colonia, calle y número" ${delivery==='delivery'?'required':''}></label><label class="full">Notas del pedido (opcional)<textarea name="notes" maxlength="300" placeholder="¿Hay algo que debamos saber?"></textarea></label><label class="full">Forma de pago<select name="payment"><option value="demo">Simulación de pago · Sin cobro</option></select></label><div class="full" id="checkoutTotal">${checkoutSummary(t)}</div><button class="primary full wide" type="submit">Confirmar pedido de demostración <span>↗</span></button></form>`);}
function checkoutSummary(t){return `<div class="summary-row"><span>Subtotal</span><strong>${money(t.subtotal)}</strong></div>${t.discount?`<div class="summary-row"><span>Descuento</span><strong>−${money(t.discount)}</strong></div>`:''}<div class="summary-row"><span>${delivery==='pickup'?'Retiro':'Envío'}</span><strong>${money(t.shipping)}</strong></div><div class="summary-row total"><span>Total demo</span><strong>${money(t.total)}</strong></div>`;}
function receipt(o){return `<div class="receipt"><p><strong>${escapeHTML(o.id)}</strong> · ${escapeHTML(new Date(o.date).toLocaleString('es-SV'))}</p><p>${o.method==='pickup'?'Retiro en tienda (demostración)':'Entrega a domicilio (demostración)'}</p>${o.items.map(p=>`<div class="summary-row"><span>${escapeHTML(p.name)} × ${p.quantity}</span><strong>${money(p.price*p.quantity)}</strong></div>`).join('')}<div class="summary-row"><span>Subtotal</span><strong>${money(o.subtotal)}</strong></div>${o.discount?`<div class="summary-row"><span>Descuento</span><strong>−${money(o.discount)}</strong></div>`:''}<div class="summary-row"><span>Envío</span><strong>${money(o.shipping)}</strong></div><div class="summary-row total"><span>Total demo</span><strong>${money(o.total)}</strong></div><p>Sin cobros ni entregas reales.</p></div>`;}
const info={delivery:{title:'Tu compra, como tú prefieras',body:'<h3>Entrega a domicilio</h3><p>En esta demostración, el envío cuesta $2.50. Es gratis cuando el subtotal de productos llega a $35, antes del cupón.</p><h3>Retiro en tienda</h3><p>Selecciona retiro para probar una compra sin costo de envío. Aún no existe una tienda ni una ruta de entrega asociada al proyecto.</p><h3>Precios transparentes</h3><p>Los importes del catálogo son precios de demostración en dólares. El resumen muestra productos, descuento y envío antes de confirmar.</p>'},help:{title:'Estamos para ayudarte',body:'<h3>¿Cómo agrego un producto?</h3><p>Pulsa + en la tarjeta. Puedes ajustar la cantidad y eliminar productos desde el carrito.</p><h3>¿Puedo pagar de verdad?</h3><p>Esta versión permite probar el proceso completo sin cobrar. Para vender de verdad será necesario conectar pagos, inventario, pedidos y logística del negocio.</p><h3>¿Dónde encuentro mis pedidos?</h3><p>Pulsa el icono de usuario o «Mis pedidos» en el pie de página. Los pedidos demo permanecen en este navegador.</p><h3>¿Cómo uso el descuento?</h3><p>Escribe BIENVENIDO10 en el carrito. Obtendrás un 10% de descuento sobre los productos, excluyendo el envío.</p>'},privacy:{title:'Tus datos, con claridad',body:'<p>Esta demo usa el almacenamiento local de tu navegador para recordar el carrito, los favoritos, la preferencia de entrega y los pedidos de prueba.</p><p>Los datos introducidos al comprar no se envían a un servidor de pedidos. No introduzcas datos de tarjeta: esta versión no los solicita ni procesa.</p><p>Las fuentes pueden cargarse desde Google Fonts. Si no están disponibles, se usan las fuentes del dispositivo.</p><p>Puedes borrar los datos de Comercio con el botón siguiente o desde los ajustes del navegador.</p><button class="primary" data-action="eraseAsk">Borrar datos de la demo</button>'}};
function orderList(){showModal(`<span class="eyebrow">TU HISTORIAL LOCAL</span><h2>Mis pedidos</h2><p>Pedidos de demostración guardados en este navegador.</p>${orders.length?orders.slice().reverse().map(o=>`<article class="order-card"><strong>${escapeHTML(o.id)}</strong><small>${escapeHTML(new Date(o.date).toLocaleString('es-SV'))}</small><p>${o.items.reduce((s,p)=>s+p.quantity,0)} unidades · ${money(o.total)} · Demo confirmada</p><button class="text-button" data-order="${escapeHTML(o.id)}">Ver resumen <span>↗</span></button></article>`).join(''):'<div class="empty"><h3>Aún no tienes pedidos</h3><p>Tu próxima buena compra comienza aquí.</p><button class="primary" data-action="catalog">Empezar mi compra</button></div>'}`);}
function locationModal(){showModal(`<span class="eyebrow">TU COMPRA, MÁS CERCA</span><h2>Elige cómo recibir</h2><p>Guarda tu preferencia de entrega para la compra de demostración.</p><form id="locationForm" class="form-grid"><label class="full">Municipio<input name="city" maxlength="60" minlength="3" value="${escapeHTML(savedLocation.city||'')}" placeholder="Ej. San Salvador" required></label><label class="full">Forma de entrega<select name="method"><option value="delivery" ${delivery==='delivery'?'selected':''}>A domicilio (demo)</option><option value="pickup" ${delivery==='pickup'?'selected':''}>Retiro en tienda (demo)</option></select></label><button class="primary full" type="submit">Guardar preferencia</button></form>`);}
function actions(name){switch(name){case 'catalog':case 'reset':browse();break;case 'offers':{const enabled=!state.offers;browse();state.offers=enabled;render();break}case 'favorites':{const enabled=!state.favoritesOnly;browse();state.favoritesOnly=enabled;render();break}case 'cart':closeDialogs();renderCart();$('#cartDialog').showModal();break;case 'checkout':checkout();break;case 'orders':orderList();break;case 'location':locationModal();break;case 'delivery':case 'help':case 'privacy':showModal(`<span class="eyebrow">COMERCIO TE ACOMPAÑA</span><h2>${info[name].title}</h2>${info[name].body}`);break;case 'coupon':navigator.clipboard?.writeText('BIENVENIDO10').then(()=>toast('Código copiado: BIENVENIDO10')).catch(()=>showModal('<h2>Tu descuento está listo</h2><p>Copia este código y aplícalo en el carrito:</p><strong>BIENVENIDO10</strong>'));if(!navigator.clipboard)showModal('<h2>Tu descuento está listo</h2><p>Copia este código en el carrito: <strong>BIENVENIDO10</strong></p>');break;case 'removeCoupon':coupon='';renderCart();toast('Cupón eliminado.');break;case 'eraseAsk':showModal('<h2>¿Borrar tus datos locales?</h2><p>Se eliminarán el carrito, los favoritos, las preferencias y los pedidos de demostración de este navegador.</p><button class="primary" data-action="eraseConfirm">Sí, borrar datos</button> <button class="text-button" data-close>Cancelar</button>');break;case 'eraseConfirm':{let ok=true;for(const key of ['cart','favorites','location','orders','subscription'])try{localStorage.removeItem('comercio-'+key)}catch{ok=false}if(!ok)return toast('No pudimos borrar todos los datos. Usa los ajustes del navegador.');cart={};favorites=[];orders=[];savedLocation={};coupon='';delivery='delivery';$('#locationLabel').innerHTML='Elegir entrega <span>⌄</span>';closeDialogs();render();toast('Datos locales eliminados.');break;}}}
document.addEventListener('click',e=>{
 const button=e.target.closest('button');if(!button)return;
 if(button.hasAttribute('data-close'))return closeDialogs();
 if(button.dataset.action)return actions(button.dataset.action);
 if(button.dataset.category){state.category=button.dataset.category;state.offers=false;state.favoritesOnly=false;browse(false);return}
 if(button.dataset.change){const p=products.find(p=>p.id===button.dataset.change);const before=cart[p.id]||0;const n=Math.max(0,Math.min(p.stock,before+Number(button.dataset.delta)));if(n)cart[p.id]=n;else delete cart[p.id];const ok=write('cart',cart);render();if(!ok)toast('Carrito actualizado para esta sesión; el navegador no permite guardarlo.');else if(n>before&&before===0)toast(`${p.name} agregado al carrito`);return}
 if(button.dataset.remove){delete cart[button.dataset.remove];write('cart',cart);render();return}
 if(button.dataset.favorite){const id=button.dataset.favorite;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];const ok=write('favorites',favorites);render();toast(ok?(favorites.includes(id)?'Guardado en tus favoritos':'Eliminado de tus favoritos'):'Favoritos actualizados para esta sesión.');return}
 if(button.dataset.detail){const p=products.find(p=>p.id===button.dataset.detail);showModal(`<div class="detail-image">${art(p.art)}</div><span class="eyebrow">${p.category}</span><h2>${p.name}</h2><p>${p.unit}. Producto de demostración para explorar tu próxima compra. Máximo ${p.stock} unidades por pedido.</p><div class="summary-row total"><span>Precio por presentación</span><strong>${money(p.price)}</strong></div><button class="primary wide" data-change="${p.id}" data-delta="1" ${(cart[p.id]||0)>=p.stock?'disabled':''}>Agregar al carrito</button>`);return}
 if(button.dataset.order){const o=orders.find(o=>o.id===button.dataset.order);if(o)showModal(`<span class="eyebrow">RESUMEN DE TU COMPRA</span><h2>Pedido de demostración</h2>${receipt(o)}<button class="primary wide" data-action="orders">Volver a mis pedidos</button>`)}
});
document.addEventListener('submit',e=>{
 if(e.target.id==='searchForm'){e.preventDefault();state.query=$('#search').value;state.category='Todos';state.offers=false;state.favoritesOnly=false;browse(false)}
 if(e.target.id==='couponForm'){e.preventDefault();const value=new FormData(e.target).get('coupon').trim().toUpperCase();if(value==='BIENVENIDO10'){coupon=value;renderCart();toast('Descuento del 10% aplicado.')}else{toast('Código no válido. Prueba BIENVENIDO10.')}}
 if(e.target.id==='locationForm'){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(!data.city.trim())return toast('Escribe tu municipio.');savedLocation=data;delivery=data.method;const ok=write('location',data);$('#locationLabel').textContent=data.city;closeDialogs();toast(ok?'Preferencia de entrega guardada.':'Preferencia guardada para esta sesión.');}
 if(e.target.id==='newsletterForm'){e.preventDefault();const email=e.target.querySelector('input').value;const ok=write('subscription',email);toast(ok?'Suscripción demo guardada. No se enviarán correos.':'Suscripción probada. No se enviarán correos.');e.target.reset();}
 if(e.target.id==='checkoutForm'){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(!data.name.trim()||(data.method==='delivery'&&!data.address.trim()))return toast('Completa tu nombre y dirección.');cart=cleanCart(cart);if(!Object.keys(cart).length)return toast('Tu carrito está vacío.');delivery=data.method;const t=totals(cart,coupon,delivery);const o={id:'COM-'+crypto.randomUUID().slice(0,8).toUpperCase(),date:new Date().toISOString(),method:data.method,customer:data,...t,items:products.filter(p=>cart[p.id]).map(p=>({id:p.id,name:p.name,price:p.price,quantity:cart[p.id]}))};const next=[...orders,o];if(!write('orders',next))return toast('No se pudo guardar el pedido. Activa el almacenamiento del navegador e inténtalo de nuevo.');orders=next;cart={};coupon='';write('cart',cart);render();showModal(`<div class="success-icon">✓</div><span class="eyebrow">TODO LISTO</span><h2>¡Gracias por tu compra demo!</h2><p>${escapeHTML(data.name)}, tu pedido de demostración está guardado en este navegador. No se ha realizado ningún cobro.</p>${receipt(o)}<button class="primary wide" data-action="orders">Ver mis pedidos <span>↗</span></button><button class="text-button" data-action="catalog">Seguir explorando</button>`);}
});
$('#search').addEventListener('input',e=>{state.query=e.target.value;state.category='Todos';state.offers=false;state.favoritesOnly=false;render()});$('#sort').addEventListener('change',e=>{state.sort=e.target.value;render()});
document.addEventListener('change',e=>{if(e.target.id==='checkoutMethod'){delivery=e.target.value;$('#addressLabel').hidden=delivery==='pickup';$('#addressLabel input').required=delivery==='delivery';$('#checkoutTotal').innerHTML=checkoutSummary(totals(cart,coupon,delivery));}});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!document.querySelector('dialog[open]')&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();$('#search').focus()}});
document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialogs()}});d.addEventListener('close',()=>{if(d.contains($('#toast'))){document.body.append($('#toast'));$('#toast').classList.remove('in-dialog','visible')}})});
if(savedLocation.city)$('#locationLabel').textContent=savedLocation.city;
render();
