const {test}=require('node:test');const assert=require('node:assert/strict');const {products,categories,cleanCart,totals,filterProducts,pageState}=require('../core.js');
test('el carrito ignora productos inexistentes y cantidades inválidas y limita existencias',()=>{assert.deepEqual(cleanCart({tomate:999,leche:-2,agua:'3',pan:1.9,falso:5,cafe:'NaN'}),{tomate:25,pan:1,agua:3})});
test('cupón y envío se calculan en centavos; límite gratis antes del descuento',()=>{assert.deepEqual(totals({tomate:2},'BIENVENIDO10'),{subtotal:350,discount:35,shipping:250,total:565});assert.deepEqual(totals({tomate:20},'BIENVENIDO10'),{subtotal:3500,discount:350,shipping:0,total:3150});assert.equal(totals({tomate:19},'BIENVENIDO10').shipping,250)});
test('cantidades menores de una unidad desaparecen',()=>{assert.deepEqual(cleanCart({agua:0.5,tomate:0,leche:null}),{})});
test('retiro y carrito vacío no cobran envío',()=>{assert.equal(totals({agua:1},'','pickup').total,85);assert.equal(totals({}).total,0);assert.equal(totals({agua:1},'INVALIDO').discount,0)});
test('búsqueda admite tildes y filtros combinados',()=>{assert.equal(filterProducts({query:'cafe'})[0].id,'cafe');assert.equal(filterProducts({query:'LACTEOS'}).length,6);assert.equal(filterProducts({category:'Panadería',offers:true}).length,2);assert.equal(filterProducts({favoritesOnly:true,favorites:['agua']})[0].id,'agua')});
test('ordenar no modifica el catálogo y los identificadores son únicos',()=>{const before=products.map(p=>p.id);const sorted=filterProducts({sort:'price-asc'});assert.equal(sorted[0].id,'agua');assert.deepEqual(products.map(p=>p.id),before);assert.equal(new Set(before).size,products.length)});
test('catálogo completo de 40 productos válidos en siete departamentos',()=>{assert.equal(products.length,40);assert.equal(categories.length,7);for(const c of categories)assert.ok(products.some(p=>p.category===c.name));for(const p of products){assert.ok(Number.isInteger(p.price)&&p.price>0);assert.ok(Number.isInteger(p.stock)&&p.stock>0);assert.ok(categories.some(c=>c.name===p.category));if(p.old)assert.ok(p.old>p.price)}});
test('las páginas de ofertas y favoritos conservan su alcance al buscar o cambiar categoría',()=>{const offerState=pageState('ofertas',{q:'carne',categoria:'Carnes y pescados'});assert.equal(offerState.offers,true);const offers=filterProducts(offerState);assert.equal(offers.length,1);assert.equal(offers[0].id,'res');const favoriteState=pageState('favoritos',{q:'pollo',categoria:'Carnes y pescados'});assert.equal(favoriteState.favoritesOnly,true);assert.equal(filterProducts({...favoriteState,favorites:[]}).length,0);assert.equal(filterProducts({...favoriteState,favorites:['pollo']})[0].id,'pollo');assert.equal(pageState('ofertas').offers,true);assert.equal(pageState('favoritos').favoritesOnly,true);assert.equal(pageState('productos',{categoria:'inexistente'}).category,'Todos')});
