import assert from 'node:assert/strict';
import {features,resample,dtw,validSequence,classifySequence,classify} from '../recognition.mjs';
const hand=Array.from({length:21},(_,i)=>({x:.3+(i%5)*.025,y:.3+Math.floor(i/5)*.04,z:0}));
const f=features(hand);assert.equal(f.length,60);
const shifted=hand.map(p=>({x:2*p.x+.1,y:2*p.y-.2,z:p.z}));
features(shifted).forEach((x,i)=>assert.ok(Math.abs(x-f[i])<1e-10));
const mirrored=hand.map(p=>({...p,x:1-p.x}));features(mirrored).forEach((x,i)=>assert.ok(Math.abs(x-f[i])<1e-10));
assert.equal(features(Array(21).fill({x:0,y:0,z:0})),null);
assert.equal(classify(hand,{TEST:Array(12).fill(f)}).label,'TEST');
assert.equal(classify(hand,{X:Array(12).fill(f),Y:Array(12).fill(f)}).label,null);
const path=n=>Array.from({length:n},(_,i)=>[i/(n-1),Math.sin(i/(n-1)*Math.PI)]);
assert.ok(dtw(resample(path(18)),resample(path(55)))<.004);
const seq=Array.from({length:24},(_,i)=>Array(62).fill(i/24));assert.ok(validSequence(seq));
assert.equal(classifySequence(seq,{A:[seq,seq]}).label,'A');
assert.equal(classifySequence(seq,{A:[seq,seq],B:[seq,seq]}).label,null);
assert.equal(classifySequence(seq,{A:[seq]}).label,null);
assert.ok(!validSequence([[NaN]]));
console.log('Recognition tests passed: scale, translation, mirror, unknown/ambiguous rejection, sequence speed normalization, import shape.');
const {isCPose,qualityOfStatic,MotionSegmenter}=await import('../recognition.mjs');
const cHand=Array.from({length:21},()=>({x:.5,y:.8,z:0}));
cHand[1]={x:.4,y:.77,z:0};cHand[2]={x:.41,y:.7,z:0};cHand[3]={x:.43,y:.62,z:0};cHand[4]={x:.48,y:.6,z:0};
for(const [base,x,y]of [[5,.44,.62],[9,.5,.6],[13,.56,.62],[17,.62,.65]]){cHand[base]={x,y,z:0};cHand[base+1]={x,y:y-.14,z:0};cHand[base+2]={x:x+.05,y:y-.19,z:0};cHand[base+3]={x:x+.11,y:y-.16,z:0};}
assert.ok(isCPose(cHand));assert.equal(classify(cHand).label,'C');
const touching=cHand.map(p=>({...p}));touching[4]={...touching[8]};assert.ok(!isCPose(touching));
assert.ok(qualityOfStatic(Array.from({length:20},()=>cHand)).ok);
assert.ok(!qualityOfStatic([cHand]).ok);
const bHand=cHand.map(p=>({...p}));for(const base of [5,9,13,17]){for(let j=1;j<=3;j++)bHand[base+j]={x:bHand[base].x,y:bHand[base].y-j*.12,z:0};}bHand[4]={x:.44,y:.61,z:0};
assert.equal(classify(bHand,{C:Array(12).fill(features(cHand))}).label,'B','Calibrating C must not disable uncalibrated B');
function segment(duration){const detector=new MotionSegmenter();let outputs=[];for(let now=0;now<duration+2000;now+=80){const dx=now<500?0:Math.min(.18,(now-500)/duration*.18);const points=cHand.map(p=>({...p,x:p.x+dx}));const result=detector.push(points,now);if(result?.frames)outputs.push(result);}return outputs;}
assert.equal(segment(1400).length,1);assert.equal(segment(3200).length,1);
const still=new MotionSegmenter();for(let i=0;i<50;i++)assert.equal(still.push(cHand,i*80),null);
still.push(null,5000);assert.equal(still.active,null);
console.log('Additional checks passed: conservative C/O distinction, C calibration preserves B, static quality, slow/fast motion segmentation, no motion for a still hand.');
