import {shareExample,loadShared} from './shared.mjs';
import {BASIC,features,classify,sequenceFeatures,classifySequence,validSequence,qualityOfStatic,MotionSegmenter} from './recognition.mjs';
const $=id=>document.getElementById(id),video=$('video'),canvas=$('overlay'),ctx=canvas.getContext('2d');
const KEY='senaletra.learning.v2';let samples={},motion={},captureSizes={},pendingExample=null,training=false,votes=[],motionHold=0;let sharedSamples={},sharedMotion={};const segmenter=new MotionSegmenter();let evaluation=[];try{evaluation=JSON.parse(localStorage.getItem('senaletra.tests.v1')||'[]').filter(x=>typeof x.label==='string'&&typeof x.correct==='boolean').slice(-50);}catch{}
function validLabel(k){return typeof k==='string'&&k.trim().length>0&&k.length<=24&&!['__proto__','constructor','prototype'].includes(k);}
function cleanData(raw){
 if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('Formato de archivo incorrecto.');
 const out={samples:{},motion:{},captureSizes:{}};
 for(const [k,v] of Object.entries(raw.samples||{}).slice(0,40))if(validLabel(k)&&Array.isArray(v))out.samples[k]=v.filter(x=>Array.isArray(x)&&x.length===60&&x.every(n=>Number.isFinite(n)&&Math.abs(n)<100)).slice(-1200);
 for(const [k,v] of Object.entries(raw.motion||{}).slice(0,40))if(validLabel(k)&&Array.isArray(v))out.motion[k]=v.filter(validSequence).slice(-50);
 for(const [k,v] of Object.entries(out.samples)){const sizes=raw.captureSizes?.[k];out.captureSizes[k]=Array.isArray(sizes)&&sizes.every(n=>Number.isInteger(n)&&n>0&&n<=1200)&&sizes.reduce((a,b)=>a+b,0)===v.length?sizes:(v.length?[v.length]:[]);}
 return out;
}
try{const raw=localStorage.getItem(KEY);if(raw){const d=cleanData(JSON.parse(raw));samples=d.samples;motion=d.motion;captureSizes=d.captureSizes;}else{samples=cleanData({samples:JSON.parse(localStorage.getItem('senaletra.samples.v1')||'{}')}).samples;}}catch{}
let model,modelLoading,stream,running=false,loading=false,detectorActive=false,raf,session=0,lastVideo=-1,lastInfer=0,points=null,candidate=null,since=0,ready=false,latched=null,text='',practice=false,target='L',capture=null,captureTimer=null;
const connections=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[0,17],[17,18],[18,19],[19,20]];
const say=s=>$('message').textContent=s;
let learningDB=null;
async function openLearningDB(){if(!globalThis.indexedDB)return null;return new Promise((resolve)=>{const r=indexedDB.open('senaletra-training',1);r.onupgradeneeded=()=>r.result.createObjectStore('learning');r.onsuccess=()=>resolve(r.result);r.onerror=()=>resolve(null);r.onblocked=()=>resolve(null);});}
async function dbRead(){if(!learningDB)return null;return new Promise(resolve=>{const t=learningDB.transaction('learning','readonly'),r=t.objectStore('learning').get(KEY);r.onsuccess=()=>resolve(r.result);r.onerror=()=>resolve(null);});}
async function save(){const data={version:2,language:'LESSA',updatedAt:Date.now(),samples,motion,captureSizes};let stored=false;try{localStorage.setItem(KEY,JSON.stringify(data));stored=localStorage.getItem(KEY)===JSON.stringify(data);}catch{}
 if(learningDB)stored=(await new Promise(resolve=>{try{const t=learningDB.transaction('learning','readwrite');t.objectStore('learning').put(data,KEY);t.oncomplete=()=>resolve(true);t.onerror=t.onabort=()=>resolve(false);}catch{resolve(false);}}))||stored;
 $('storageStatus').textContent=stored?'✓ Datos guardados en este navegador. Puedes cerrar y volver.':'No se pudo guardar. Exporta tus ejemplos antes de cerrar.';return stored;}
learningDB=await openLearningDB();const restored=await dbRead();if(restored){try{const local=JSON.parse(localStorage.getItem(KEY)||'null');if(!local||!(local.updatedAt>restored.updatedAt)){const d=cleanData(restored);samples=d.samples;motion=d.motion;captureSizes=d.captureSizes;}}catch{const d=cleanData(restored);samples=d.samples;motion=d.motion;captureSizes=d.captureSizes;}}

function counts(){
 const keys=[...new Set([...Object.keys(samples),...Object.keys(motion)])].filter(k=>(samples[k]?.length||0)+(motion[k]?.length||0)>0).sort();$('sampleCounts').replaceChildren();$('trainedCount').textContent=keys.length;$('testScore').textContent=evaluation.length?`${evaluation.filter(x=>x.correct).length} / ${evaluation.length}`:'—';refreshAlphabetStatus();
 if(!keys.length){$('sampleCounts').textContent='Todavía no has guardado ejemplos.';return;}
 for(const k of keys){const d=document.createElement('div');d.textContent=`${k} · ${captureSizes[k]?.length||((samples[k]?.length||0)?1:0)} capturas de posición (${samples[k]?.length||0} fotogramas) / ${motion[k]?.length||0} movimientos${(motion[k]?.length||0)===1?' · falta otro movimiento':''}`;$('sampleCounts').append(d);}
}
function setResult(label,source){$('letter').textContent=label||'—';$('letter').classList.toggle('long',!!label&&label.length>2);$('stable').textContent=source;}
function resetDetection(){votes=[];segmenter.reset();motionHold=0;points=null;candidate=null;since=0;ready=false;$('confirm').disabled=true;$('progress').style.width='0';setResult(null,'Muestra una mano completa');}
function cancelCapture(message='Captura cancelada.'){segmenter.reset();clearTimeout(captureTimer);capture=null;$('capture').disabled=false;$('finishCapture').disabled=true;$('motionFloating').hidden=true;$('trainingStatus').textContent=message;}
function alertCamera(message){$('cameraAlert').hidden=false;$('cameraErrorText').textContent=message;}
function stop(){session++;running=false;detectorActive=false;cancelAnimationFrame(raf);if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;resetDetection();cancelCapture();ctx.clearRect(0,0,canvas.width,canvas.height);$('empty').hidden=false;$('pause').textContent='Reanudar';$('pause').disabled=loading;$('switch').disabled=true;$('status').textContent='Cámara apagada';$('stable').textContent='Activa la cámara para comenzar';}
async function loadDetector(){if(model)return model;if(modelLoading)return modelLoading;modelLoading=(async()=>{let vision,wasm='./vendor/wasm',asset='./vendor/hand_landmarker.task';try{vision=await import('./vendor/vision_bundle.mjs');}catch{vision=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/vision_bundle.mjs');wasm='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm';asset='https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task';}const {FilesetResolver,HandLandmarker}=vision;const files=await FilesetResolver.forVisionTasks(wasm);return HandLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:asset,delegate:'CPU'},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.65,minHandPresenceConfidence:.65,minTrackingConfidence:.6});})();try{model=await modelLoading;return model;}finally{modelLoading=null;}}
function timeout(p,ms){let timer;return Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('El detector tarda demasiado. Reintenta la carga.')),ms);})]).finally(()=>clearTimeout(timer));}
async function enableDetector(){const token=session;$('retryDetector').disabled=true;try{await timeout(loadDetector(),30000);if(!running||session!==token)return;detectorActive=true;$('cameraAlert').hidden=true;lastVideo=-1;lastInfer=0;$('status').textContent='Buscando mano';cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);}catch(e){if(running&&session===token){detectorActive=false;alertCamera('La cámara está activa, pero el detector no pudo cargar. '+e.message);$('status').textContent='Detector pendiente';}}finally{$('retryDetector').disabled=false;}}
async function start(deviceId){
 if(loading)return;loading=true;const token=++session;let acquired;$('cameraAlert').hidden=true;$('start').disabled=true;$('pause').disabled=true;$('start').textContent='Solicitando permiso…';$('status').textContent='Esperando permiso';
 try{
 if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia)throw Error('Abre este sitio mediante HTTPS o localhost para usar la cámara.');
 acquired=await navigator.mediaDevices.getUserMedia({video:deviceId?{deviceId:{exact:deviceId},width:{ideal:960},height:{ideal:600}}:{width:{ideal:960},height:{ideal:600},facingMode:'user'},audio:false});
 if(token!==session){acquired.getTracks().forEach(t=>t.stop());return;}
 stream=acquired;video.srcObject=stream;await video.play();if(token!==session)return;
 running=true;latched=null;stream.getVideoTracks()[0].addEventListener('ended',()=>{if(running&&token===session){stop();alertCamera('La cámara se desconectó. Conéctala y vuelve a activarla.');}});
 $('empty').hidden=true;$('pause').disabled=false;$('pause').textContent='Pausar';$('switch').disabled=false;$('status').textContent='Cargando detector';setResult(null,'Preparando reconocimiento…');void enableDetector();
 }catch(e){if(token!==session)return;if(acquired)acquired.getTracks().forEach(t=>t.stop());stop();const messages={NotAllowedError:'Permite el acceso a la cámara desde los permisos del navegador.',NotFoundError:'No se encontró una cámara conectada.',NotReadableError:'La cámara está ocupada. Cierra otras aplicaciones que la estén usando.'};alertCamera(messages[e.name]||e.message);say(messages[e.name]||e.message);}
 finally{loading=false;$('start').disabled=false;$('start').textContent='Activar cámara ↗';$('pause').disabled=!running&&!!document.hidden;}
}
function draw(p){if(canvas.width!==video.videoWidth||canvas.height!==video.videoHeight){canvas.width=video.videoWidth;canvas.height=video.videoHeight;}ctx.clearRect(0,0,canvas.width,canvas.height);if(!p)return;ctx.strokeStyle='#b4f0cb';ctx.fillStyle='#d4ffe0';ctx.lineWidth=2;for(const [a,b] of connections){ctx.beginPath();ctx.moveTo(p[a].x*canvas.width,p[a].y*canvas.height);ctx.lineTo(p[b].x*canvas.width,p[b].y*canvas.height);ctx.stroke();}for(const q of p){ctx.beginPath();ctx.arc(q.x*canvas.width,q.y*canvas.height,3,0,Math.PI*2);ctx.fill();}}
function processCapture(now){
 if(!capture)return;
 const c=capture;
 if(now<c.starts){const n=Math.ceil((c.starts-now)/1000);$('trainingStatus').textContent=`Prepárate: ${n}…`;$('stable').textContent=`Prepárate: ${n}…`;return;}
 if(points&&features(points)){c.frames.push(points.map(p=>({...p})));c.misses=0;}else c.misses++;
 if(c.mode!=='static'&&c.misses>5&&c.frames.length){cancelCapture('Captura cancelada: la mano salió del encuadre. Repite la seña completa.');say('Mantén una sola mano visible durante todo el movimiento.');return;}
 const remaining=Math.max(0,Math.ceil((c.ends-now)/1000));$('trainingStatus').textContent=c.mode==='static'?`Mantén ${c.label} · ${remaining} s`:`Realiza ${c.label||'la seña'} y pulsa Terminar · máximo ${remaining} s`;
 $('stable').textContent=c.mode==='static'?'Capturando posición…':'Capturando movimiento…';
 if(now>=c.ends)finishCapture();
}
function loop(now){if(!running||!detectorActive)return;try{if(video.readyState>=2&&video.currentTime!==lastVideo&&now-lastInfer>=50){lastVideo=video.currentTime;lastInfer=now;const result=model.detectForVideo(video,now);points=result.landmarks.length===1?result.landmarks[0]:null;draw(points);
 if(capture){$('status').textContent=points?'Capturando ejemplo':'Muestra una sola mano';processCapture(now);}
 else if(!points){if(now<motionHold){raf=requestAnimationFrame(loop);return;}resetDetection();latched=null;$('status').textContent=result.landmarks.length>1?'Usa una sola mano':'Buscando mano';$('stable').textContent=result.landmarks.length>1?'Esta versión aprende señas de una mano':'Muestra una mano completa';}
 else{
 $('status').textContent='Mano detectada';
 if($('autoMotion').checked&&!training&&!practice&&Object.values(recognitionMotion()).some(v=>v.length>=2)){
 const segment=segmenter.push(points,now);if(segment?.frames){const seq=sequenceFeatures(segment.frames);if(seq){const r=classifySequence(seq,recognitionMotion());if(r.label){holdMotionResult(r);$('status').textContent='Movimiento reconocido';}}}
 if(segmenter.active){$('status').textContent='Siguiendo movimiento';$('stable').textContent='Termina la seña y mantén la mano quieta';$('confirm').disabled=true;raf=requestAnimationFrame(loop);return;}
 }
 if(now<motionHold){raf=requestAnimationFrame(loop);return;}
 const raw=classify(points,recognitionSamples());votes.push(raw.label);votes=votes.slice(-9);const tallies={};for(const k of votes)if(k)tallies[k]=(tallies[k]||0)+1;const winner=Object.entries(tallies).sort((a,b)=>b[1]-a[1])[0];const r={...raw,label:winner&&winner[1]>=7?winner[0]:null};if(r.label&&r.label!==raw.label)r.source='Coincidencia estable · varios fotogramas';if(r.label!==candidate){candidate=r.label;since=now;ready=false;}const elapsed=now-since;ready=!!candidate&&elapsed>=800;setResult(candidate,candidate?(ready?r.source:'Mantén la posición…'):r.source);$('confirm').disabled=!ready;$('progress').style.width=(candidate?Math.min(100,elapsed/15):0)+'%';if(candidate&&latched&&candidate!==latched&&ready)latched=null;if(!training&&$('auto').checked&&elapsed>=1500&&ready&&latched!==candidate)confirm();}
 }}catch(e){detectorActive=false;resetDetection();cancelCapture();alertCamera('Se detuvo el detector. El video sigue activo; pulsa Reintentar detector.');$('status').textContent='Detector detenido';console.error(e);}raf=running&&detectorActive?requestAnimationFrame(loop):null;}
function render(){$('word').replaceChildren();if(!text){const p=document.createElement('span');p.className='placeholder';p.textContent='Las palabras empiezan aquí…';$('word').append(p);}else $('word').textContent=text;$('charCount').textContent=`${text.length} / 200`;$('word').scrollTop=$('word').scrollHeight;}
function confirm(){if(!ready||!candidate||capture)return;if(practice){$('practiceFeedback').textContent=candidate===target?'¡Correcto! Prueba otra letra.':`Se detectó ${candidate}. Intenta ${target}.`;latched=candidate;return;}const add=candidate.length===1?candidate:((text&&!text.endsWith(' ')?' ':'')+candidate+' ');if(text.length+add.length>200){say('El mensaje llegó al límite de 200 caracteres.');return;}text+=add;latched=candidate;render();say('Resultado añadido. Retira la mano para repetir en modo automático.');}
function label(){return ($('customLabel').value.trim()||$('trainLetter').value).toLocaleUpperCase('es');}
function beginCapture(mode,test=false){if(!running||!detectorActive||!points){$('trainingStatus').textContent='Activa la cámara y muestra una sola mano antes de capturar.';say('Activa la cámara y muestra una mano antes de capturar.');return false;}if(capture||pendingExample){$('trainingStatus').textContent='Guarda o descarta el ejemplo pendiente antes de capturar otro.';return false;}const k=label();if(!test&&!validLabel(k)){say('Escribe una etiqueta válida de hasta 24 caracteres.');return false;}const now=performance.now();capture={mode,test,label:test?null:k,starts:now+1800,ends:now+1800+(mode==='static'?2500:12000),frames:[],misses:0,evaluate:!test&&$('trainingPurpose').value==='evaluate'};votes=[];segmenter.reset();$('capture').disabled=true;$('confirm').disabled=true;$('finishCapture').disabled=mode==='static';if(test){tab('translate');$('motionFloating').hidden=false;}return true;}
function evaluateExample(c){
 let result;
 if(c.mode==='static'){
 const votes=c.frames.map(p=>classify(p,recognitionSamples()).label).filter(Boolean),counts={};for(const k of votes)counts[k]=(counts[k]||0)+1;
 const ranked=Object.entries(counts).sort((a,b)=>b[1]-a[1]);result={label:ranked[0]&&ranked[0][1]>=c.frames.length*.65?ranked[0][0]:null};
 }else result=classifySequence(sequenceFeatures(c.frames),recognitionMotion());
 const correct=result.label===c.label;evaluation.push({label:c.label,predicted:result.label,correct,date:Date.now()});evaluation=evaluation.slice(-50);try{localStorage.setItem('senaletra.tests.v1',JSON.stringify(evaluation));}catch{}
 $('evaluationResult').textContent=`${correct?'✓ Coincidencia correcta':'Revisar'} · Esperada: ${c.label} · Detectada: ${result.label||'sin coincidencia clara'}. Este ejemplo no se guardó.`;$('evaluationResult').className=correct?'testSuccess':'testNeedsWork';counts();
}
function holdMotionResult(r){candidate=r.label;ready=!!candidate;since=performance.now();motionHold=performance.now()+3500;setResult(candidate,r.source);$('confirm').disabled=!ready;$('progress').style.width='0';say(r.label?`Movimiento reconocido: ${r.label}. Confirma para añadirlo.`:r.source);segmenter.reset();}
function finishCapture(){
 if(!capture)return;const c=capture;if(performance.now()<c.starts){say('Espera a que termine la cuenta atrás.');return;}capture=null;$('capture').disabled=false;$('finishCapture').disabled=true;$('motionFloating').hidden=true;
 const fs=c.frames.map(features).filter(Boolean);if(fs.length<12){$('trainingStatus').textContent='Captura demasiado corta: faltan fotogramas válidos. Repite la seña.';say('Mantén una mano completa visible durante la captura.');return;}
 if(c.mode==='static'){const q=qualityOfStatic(c.frames);if(!q.ok){$('trainingStatus').textContent=q.reason;return;}}
 const seq=c.mode==='motion'?sequenceFeatures(c.frames):null;
 if(c.test){const r=classifySequence(seq,recognitionMotion());holdMotionResult(r);detectorActive=false;cancelAnimationFrame(raf);$('status').textContent='Resultado de movimiento';$('retryDetector').textContent='Continuar detección';alertCamera('El resultado queda en pantalla para que lo confirmes. Pulsa Continuar detección cuando termines.');return;}
 if(c.evaluate){evaluateExample(c);$('trainingStatus').textContent='Prueba terminada; no se utilizó para entrenar.';return;}
 pendingExample={label:c.label,mode:c.mode,values:c.mode==='static'?fs:seq};$('captureReview').hidden=false;$('captureSummary').textContent=`${c.label} · ${c.mode==='static'?fs.length+' fotogramas estables':'movimiento completo'} · listo para revisar`;$('trainingStatus').textContent='Falta guardar: pulsa Guardar ejemplo para conservar esta captura.';$('capture').disabled=true;$('captureReview').scrollIntoView?.({behavior:'smooth',block:'nearest'});
}
function discardPending(message='Ejemplo descartado.'){pendingExample=null;$('captureReview').hidden=true;$('capture').disabled=!!capture;$('capture').textContent='Capturar otro ejemplo';$('trainingStatus').textContent=message;}
$('saveCapture').onclick=async()=>{if(!pendingExample)return;const c=pendingExample;if(!c.applied){if(c.mode==='static'){const values=c.values.filter((_,i)=>i%Math.max(1,Math.ceil(c.values.length/24))===0);samples[c.label]=[...(samples[c.label]||[]),...values];captureSizes[c.label]=[...(captureSizes[c.label]||((samples[c.label].length-values.length)?[samples[c.label].length-values.length]:[])),values.length];while(samples[c.label].length>1200||captureSizes[c.label].length>50){samples[c.label].splice(0,captureSizes[c.label].shift());}}else motion[c.label]=[...(motion[c.label]||[]),c.values].slice(-50);c.applied=true;}$('saveCapture').disabled=true;const stored=await save();if(!stored){$('saveCapture').disabled=false;$('trainingStatus').textContent='El ejemplo está en memoria, pero no se guardó. Exporta una copia o reintenta guardar.';counts();return;}if($('shareTraining').checked){$('cloudStatus').textContent='Guardando ejemplo compartido…';try{await shareExample(c.label,c.mode,c.values);$('cloudStatus').textContent=`✓ ${c.label}: ejemplo guardado en Supabase.`;}catch(e){$('cloudStatus').textContent=e.message+' El ejemplo queda local; usa Compartir ejemplos de esta letra para reintentar.';}}$('saveCapture').disabled=false;discardPending(`${c.label}: ejemplo añadido${stored?' y guardado en este navegador':' para esta sesión'}. Puedes capturar otro ejemplo de ${c.label}; se acumulará con los anteriores.`);counts();updateTrainingReference();};
$('discardCapture').onclick=()=>discardPending();
$('start').onclick=()=>start();$('pause').onclick=()=>running?stop():start();$('confirm').onclick=confirm;$('retryDetector').onclick=()=>running?enableDetector():start();
$('switch').onclick=async()=>{try{const devices=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='videoinput');if(devices.length<2){say('Solo hay una cámara disponible.');return;}const current=stream?.getVideoTracks()[0].getSettings().deviceId;const next=devices[(devices.findIndex(d=>d.deviceId===current)+1)%devices.length];stop();await start(next.deviceId);}catch{say('No se pudo cambiar de cámara.');}};
function mirror(){video.classList.toggle('mirror',$('mirror').checked);canvas.classList.toggle('mirror',$('mirror').checked);}$('mirror').onchange=mirror;mirror();
$('erase').onclick=()=>{text=text.slice(0,-1);render();};$('space').onclick=()=>{if(text&&text.length<200&&!text.endsWith(' ')){text+=' ';render();}};$('clear').onclick=()=>{if(!text||window.confirm('¿Borrar todo el mensaje?')){text='';render();}};
$('copy').onclick=async()=>{if(!text.trim()){say('Primero construye un mensaje.');return;}try{await navigator.clipboard.writeText(text);say('Mensaje copiado.');}catch{say('No se pudo copiar. Selecciona el mensaje y cópialo manualmente.');}};
$('speak').onclick=()=>{if(!text.trim()){say('Primero construye un mensaje.');return;}if(!('speechSynthesis'in window)){say('El navegador no admite lectura en voz alta.');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang==='es-SV')||voices.find(v=>v.lang.startsWith('es'))||null;u.lang=u.voice?.lang||'es-SV';u.rate=.9;u.onerror=()=>say('No se pudo reproducir la voz. Revisa las voces disponibles.');speechSynthesis.speak(u);};
function tab(name){
 if(capture&&!capture.test)cancelCapture('Captura cancelada al cambiar de apartado.');
 training=name==='train';practice=name==='practice';$('translateView').hidden=name==='learn';$('learnView').hidden=name!=='learn';$('trainView').hidden=!training;document.querySelector('.results').hidden=training;$('practiceBar').hidden=!practice;
 document.querySelector('.workspace').classList.toggle('trainingWorkspace',training);
 for(const b of document.querySelectorAll('[data-tab]'))b.classList.toggle('active',b.dataset.tab===name);latched=null;votes=[];segmenter.reset();$('practiceFeedback').textContent='';
 $('viewDescription').textContent=training?'Consulta, captura, revisa y evalúa tus señas desde este apartado.':'';
 if(name==='learn'&&running){stop();say('Cámara pausada al abrir las referencias.');}
 if(training){counts();updateTrainingReference();}
}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>tab(b.dataset.tab);
$('nextTarget').onclick=()=>{const available=[...new Set([...BASIC,...Object.keys(samples).filter(k=>k.length===1&&samples[k].length>=12)])].filter(k=>k!==target);target=available[Math.floor(Math.random()*available.length)];$('target').textContent=target;latched=null;$('practiceFeedback').textContent='';};
function settings(){tab('train');}$('settingsButton').onclick=settings;$('trainShortcut').onclick=settings;
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();
for(const k of 'ABCDEFGHIJKLMNÑOPQRSTUVWXYZ'){const o=document.createElement('option');o.value=o.textContent=k;$('trainLetter').append(o);}
$('capture').onclick=()=>beginCapture($('captureMode').value);$('finishCapture').onclick=finishCapture;$('motionFloating').onclick=finishCapture;
$('settings').addEventListener('close',()=>{if(capture&&!capture.test)cancelCapture();});
$('testMotion').onclick=()=>{if(!Object.values(recognitionMotion()).some(v=>v.length>=2)){$('trainingStatus').textContent='Guarda primero al menos 2 movimientos de una misma seña.';return;}beginCapture('motion',true);};
$('deleteLabel').onclick=async()=>{const k=label();if(window.confirm(`¿Borrar los ejemplos de ${k}?`)){discardPending('');if(capture)cancelCapture();delete samples[k];delete motion[k];delete captureSizes[k];await save();counts();resetDetection();$('trainingStatus').textContent=`Ejemplos de ${k} borrados.`;}};
$('exportSamples').onclick=()=>{const blob=new Blob([JSON.stringify({version:2,language:'LESSA',samples,motion,captureSizes},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='senaletra-mis-ejemplos.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('importSamples').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>6*1024*1024)throw Error('El archivo supera 6 MB.');const raw=JSON.parse(await f.text());if(raw.version!==2||raw.language!=='LESSA')throw Error('Importa una exportación de SeñaLetra LESSA versión 2.');const d=cleanData(raw);if(!Object.keys(d.samples).length&&!Object.keys(d.motion).length)throw Error('No hay ejemplos válidos en este archivo.');if(!window.confirm('¿Añadir estos ejemplos? Las señas con el mismo nombre se combinarán.'))return;if(capture)cancelCapture();for(const [k,v]of Object.entries(d.samples)){captureSizes[k]=[...(captureSizes[k]||((samples[k]?.length)?[samples[k].length]:[])),...d.captureSizes[k]];samples[k]=[...(samples[k]||[]),...v];while(samples[k].length>1200||captureSizes[k].length>50)samples[k].splice(0,captureSizes[k].shift());}for(const [k,v]of Object.entries(d.motion))motion[k]=[...(motion[k]||[]),...v].slice(-50);const stored=await save();counts();resetDetection();$('trainingStatus').textContent=stored?'Ejemplos importados y guardados. Comprueba las señas antes de usarlas.':'Importados en memoria. Exporta una copia: el navegador no pudo guardarlos.';}catch(e){$('trainingStatus').textContent=e.message;}finally{e.target.value='';}};
window.addEventListener('pagehide',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden&&(running||loading)){stop();say('Cámara pausada al cambiar de pestaña.');}});counts();

// Restore the original in-site alphabet and individual reference dialogs.
const alphabetLabels=['A','B','C','CH','D','E','F','G','H','I','J','K','L','LL','M','N','Ñ','O','P','Q','R','RR','S','T','U','V','W','X','Y','Z'];
const movingLabels=['J','LL','Ñ','RR','Z'];let detailLabel='A';
function detail(k){detailLabel=k;$('detailTitle').textContent='Letra '+k;$('detailImage').src=`assets/${k}.png`;$('detailImage').alt=`Referencia educativa LESSA de ${k}, Módulo 2`;$('detailText').textContent=movingLabels.includes(k)?'La lámina indica movimiento. Captura ejemplos completos y utiliza Reconocer movimiento.':BASIC.includes(k)?'Hay reglas iniciales experimentales para esta letra. Si no coincide con la referencia, calibra tu posición antes de utilizarla.':'Guarda ejemplos personales de esta letra desde Mi calibración para reconocerla.';$('detail').showModal();}
for(const k of alphabetLabels){const b=document.createElement('button'),img=document.createElement('img'),name=document.createElement('strong');b.dataset.letter=k;img.src=`assets/${k}.png`;img.alt=`Seña de ${k} según la referencia educativa LESSA`;img.loading='lazy';name.textContent=k;b.append(img,name);const state=document.createElement('small');state.className='alphabetState';b.append(state);if(movingLabels.includes(k)){const badge=document.createElement('small');badge.textContent='Movimiento';b.append(badge);}b.onclick=()=>detail(k);$('alphabet').append(b);}
$('guideButton').onclick=()=>$('guide').showModal();
$('guide').querySelector('[data-close]').onclick=()=>$('guide').close();$('detail').querySelector('[data-close]').onclick=()=>$('detail').close();
$('fullAlphabet').onclick=()=>window.open('guia.html','_blank','noopener');$('printGuide').onclick=()=>window.open('guia.html','_blank','noopener');
$('calibrateFromGuide').onclick=()=>{$('detail').close();$('guide').close();$('customLabel').value='';if(![...$('trainLetter').options].some(o=>o.value===detailLabel)){const o=document.createElement('option');o.value=o.textContent=detailLabel;$('trainLetter').append(o);}$('trainLetter').value=detailLabel;$('captureMode').value=movingLabels.includes(detailLabel)?'motion':'static';settings();};
for(const k of ['CH','LL','RR']){const o=document.createElement('option');o.value=o.textContent=k;$('trainLetter').append(o);}

function updateTrainingReference(){
 const k=label(),known=alphabetLabels.includes(k),moving=movingLabels.includes(k);$('trainingImage').hidden=!known;if(known){$('trainingImage').src=`assets/${k}.png`;$('trainingImage').alt=`Referencia LESSA de ${k}`;}
 $('trainingLabel').textContent=`${k} · ${$('captureMode').value==='motion'?'movimiento':'posición'}`;
 $('trainingInstructions').textContent=$('captureMode').value==='motion'?'Espera la cuenta atrás, realiza una seña completa y pulsa Terminar. Captura ejemplos a distintas velocidades.':'Espera la cuenta atrás y mantén la misma posición durante 2,5 segundos.';
 const n=motion[k]?.length||0,stat=samples[k]?.length||0;$('exampleCount').textContent=`${k}: ${captureSizes[k]?.length|| (stat?1:0)} capturas de posición · ${n} movimientos guardados (hasta 50 por tipo).`;$('availabilityBadge').textContent=$('captureMode').value==='motion'?(n>=2?`${n} movimientos · disponible`:n===1?'1 movimiento · falta otro ejemplo':'Movimiento · necesita entrenamiento'):(stat>=12?`${stat} fotogramas · calibrada`:BASIC.includes(k)?'Regla inicial experimental':'Posición · necesita entrenamiento');
}
$('trainLetter').onchange=()=>{$('customLabel').value='';$('captureMode').value=movingLabels.includes(label())?'motion':'static';updateTrainingReference();};
$('customLabel').oninput=updateTrainingReference;$('captureMode').onchange=updateTrainingReference;
$('trainingGuide').onclick=()=>{const k=label();if(alphabetLabels.includes(k))detail(k);else $('guide').showModal();};
$('autoMotion').onchange=()=>{segmenter.reset();motionHold=0;};
updateTrainingReference();

function refreshAlphabetStatus(){for(const b of document.querySelectorAll('#alphabet button')){const k=b.dataset.letter,stat=(samples[k]?.length||0)>=12,mov=(motion[k]?.length||0)>=2;b.querySelector('.alphabetState').textContent=mov?'Movimiento entrenado':stat?'Posición calibrada':BASIC.includes(k)?'Inicial · experimental':'Por entrenar';}}
refreshAlphabetStatus();

function recognitionSamples(){const out={...sharedSamples};for(const [k,v]of Object.entries(samples))out[k]=[...(out[k]||[]),...v];return out;}
function recognitionMotion(){const out={...sharedMotion};for(const [k,v]of Object.entries(motion))out[k]=[...(out[k]||[]),...v];return out;}
$('uploadShared').onclick=async()=>{const k=label();$('uploadShared').disabled=true;let uploaded=0;try{let offset=0;const sizes=captureSizes[k]||((samples[k]?.length)?[samples[k].length]:[]);for(const size of sizes){await shareExample(k,'static',samples[k].slice(offset,offset+size));offset+=size;uploaded++;}for(const seq of motion[k]||[]){await shareExample(k,'motion',seq);uploaded++;}$('cloudStatus').textContent=uploaded?`✓ ${uploaded} ejemplos de ${k} enviados a Supabase. Los repetidos no se duplican.`:'No hay ejemplos locales de esta letra para compartir.';}catch(e){$('cloudStatus').textContent=`${uploaded} enviados. ${e.message} Puedes reintentar sin duplicarlos.`;}finally{$('uploadShared').disabled=false;}};
$('loadShared').onclick=async()=>{const k=label();$('loadShared').disabled=true;try{const rows=await loadShared(k),positions=[],movements=[];for(const row of rows){const d=cleanData(row.mode==='static'?{samples:{[k]:row.values}}:{motion:{[k]:[row.values]}});if(row.mode==='static')positions.push(...(d.samples[k]||[]));else movements.push(...(d.motion[k]||[]));}sharedSamples[k]=positions;sharedMotion[k]=movements;$('cloudStatus').textContent=`${rows.length} ejemplos compartidos de ${k} cargados para reconocer. No validados; comprueba el resultado.`;resetDetection();}catch(e){$('cloudStatus').textContent=e.message;}finally{$('loadShared').disabled=false;}};
