import {BASIC,features,classify,sequenceFeatures,classifySequence,validSequence} from './recognition.mjs';
const $=id=>document.getElementById(id),video=$('video'),canvas=$('overlay'),ctx=canvas.getContext('2d');
const KEY='senaletra.learning.v2';let samples={},motion={};
function validLabel(k){return typeof k==='string'&&k.trim().length>0&&k.length<=24&&!['__proto__','constructor','prototype'].includes(k);}
function cleanData(raw){
 if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('Formato de archivo incorrecto.');
 const out={samples:{},motion:{}};
 for(const [k,v] of Object.entries(raw.samples||{}).slice(0,40))if(validLabel(k)&&Array.isArray(v))out.samples[k]=v.filter(x=>Array.isArray(x)&&x.length===60&&x.every(n=>Number.isFinite(n)&&Math.abs(n)<100)).slice(-240);
 for(const [k,v] of Object.entries(raw.motion||{}).slice(0,40))if(validLabel(k)&&Array.isArray(v))out.motion[k]=v.filter(validSequence).slice(-20);
 return out;
}
try{const raw=localStorage.getItem(KEY);if(raw){const d=cleanData(JSON.parse(raw));samples=d.samples;motion=d.motion;}else{samples=cleanData({samples:JSON.parse(localStorage.getItem('senaletra.samples.v1')||'{}')}).samples;}}catch{}
let model,modelLoading,stream,running=false,loading=false,detectorActive=false,raf,session=0,lastVideo=-1,lastInfer=0,points=null,candidate=null,since=0,ready=false,latched=null,text='',practice=false,target='L',capture=null,captureTimer=null;
const connections=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[0,17],[17,18],[18,19],[19,20]];
const say=s=>$('message').textContent=s;
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:2,language:'LESSA',samples,motion}));return true;}catch{say('Ejemplos disponibles en esta sesión; no se pudieron guardar en el navegador.');return false;}}
function counts(){
 const keys=[...new Set([...Object.keys(samples),...Object.keys(motion)])].sort();$('sampleCounts').replaceChildren();
 if(!keys.length){$('sampleCounts').textContent='Todavía no has guardado ejemplos.';return;}
 for(const k of keys){const d=document.createElement('div');d.textContent=`${k} · ${samples[k]?.length||0} posiciones / ${motion[k]?.length||0} movimientos`;$('sampleCounts').append(d);}
}
function setResult(label,source){$('letter').textContent=label||'—';$('letter').classList.toggle('long',!!label&&label.length>2);$('stable').textContent=source;}
function resetDetection(){points=null;candidate=null;since=0;ready=false;$('confirm').disabled=true;$('progress').style.width='0';setResult(null,'Muestra una mano completa');}
function cancelCapture(message='Captura cancelada.'){clearTimeout(captureTimer);capture=null;$('capture').disabled=false;$('finishCapture').disabled=true;$('motionFloating').hidden=true;$('trainingStatus').textContent=message;}
function alertCamera(message){$('cameraAlert').hidden=false;$('cameraErrorText').textContent=message;}
function stop(){session++;running=false;detectorActive=false;cancelAnimationFrame(raf);if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;resetDetection();cancelCapture();ctx.clearRect(0,0,canvas.width,canvas.height);$('empty').hidden=false;$('pause').textContent='Reanudar';$('pause').disabled=loading;$('switch').disabled=true;$('status').textContent='Cámara apagada';$('stable').textContent='Activa la cámara para comenzar';}
async function loadDetector(){if(model)return model;if(modelLoading)return modelLoading;modelLoading=(async()=>{let vision,wasm='./vendor/wasm',asset='./vendor/hand_landmarker.task';try{vision=await import('./vendor/vision_bundle.mjs');}catch{vision=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/vision_bundle.mjs');wasm='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm';asset='https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task';}const {FilesetResolver,HandLandmarker}=vision;const files=await FilesetResolver.forVisionTasks(wasm);return HandLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:asset,delegate:'CPU'},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.65,minHandPresenceConfidence:.65,minTrackingConfidence:.6});})();try{model=await modelLoading;return model;}finally{modelLoading=null;}}
function timeout(p,ms){let timer;return Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('El detector tarda demasiado. Reintenta la carga.')),ms);})]).finally(()=>clearTimeout(timer));}
async function enableDetector(){const token=session;$('retryDetector').disabled=true;try{await timeout(loadDetector(),30000);if(!running||session!==token)return;detectorActive=true;$('cameraAlert').hidden=true;lastVideo=-1;lastInfer=0;$('status').textContent='Buscando mano';cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);}catch(e){if(running&&session===token){detectorActive=false;alertCamera('La cámara está activa, pero el detector no pudo cargar. '+e.message);$('status').textContent='Detector pendiente';}}finally{$('retryDetector').disabled=false;}}
async function start(deviceId){
 if(loading)return;loading=true;const token=++session;let acquired;$('cameraAlert').hidden=true;$('start').disabled=true;$('pause').disabled=true;$('start').textContent='Solicitando permiso…';$('status').textContent='Esperando permiso';
 try{
 if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia)throw Error('Abre este sitio mediante HTTPS o localhost para usar la cámara.');
 acquired=await navigator.mediaDevices.getUserMedia({video:deviceId?{deviceId:{exact:deviceId},width:{ideal:960},height:{ideal:600}}:{width:{ideal:960},height:{ideal:600},facingMode:'user'},audio:false});
 if(token!==session){acquired.getTracks().forEach(t=>t.stop());return;}
 stream=acquired;video.srcObject=stream;await video.play();if(token!==session)return;
 running=true;latched=null;stream.getVideoTracks()[0].addEventListener('ended',()=>{if(running&&token===session){stop();alertCamera('La cámara se desconectó. Conéctala y vuelve a activarla.');}});
 $('empty').hidden=true;$('pause').disabled=false;$('pause').textContent='Pausar';$('switch').disabled=false;$('status').textContent='Cargando detector';setResult(null,'Preparando reconocimiento…');void enableDetector();
 }catch(e){if(token!==session)return;if(acquired)acquired.getTracks().forEach(t=>t.stop());stop();const messages={NotAllowedError:'Permite el acceso a la cámara desde los permisos del navegador.',NotFoundError:'No se encontró una cámara conectada.',NotReadableError:'La cámara está ocupada. Cierra otras aplicaciones que la estén usando.'};alertCamera(messages[e.name]||e.message);say(messages[e.name]||e.message);}
 finally{loading=false;$('start').disabled=false;$('start').textContent='Activar cámara ↗';$('pause').disabled=!running&&!!document.hidden;}
}
function draw(p){if(canvas.width!==video.videoWidth||canvas.height!==video.videoHeight){canvas.width=video.videoWidth;canvas.height=video.videoHeight;}ctx.clearRect(0,0,canvas.width,canvas.height);if(!p)return;ctx.strokeStyle='#b4f0cb';ctx.fillStyle='#d4ffe0';ctx.lineWidth=2;for(const [a,b] of connections){ctx.beginPath();ctx.moveTo(p[a].x*canvas.width,p[a].y*canvas.height);ctx.lineTo(p[b].x*canvas.width,p[b].y*canvas.height);ctx.stroke();}for(const q of p){ctx.beginPath();ctx.arc(q.x*canvas.width,q.y*canvas.height,3,0,Math.PI*2);ctx.fill();}}
function processCapture(now){
 if(!capture)return;
 const c=capture;
 if(now<c.starts){const n=Math.ceil((c.starts-now)/1000);$('trainingStatus').textContent=`Prepárate: ${n}…`;$('stable').textContent=`Prepárate: ${n}…`;return;}
 if(points&&features(points)){c.frames.push(points.map(p=>({...p})));c.misses=0;}else c.misses++;
 if(c.mode!=='static'&&c.misses>5&&c.frames.length){cancelCapture('Captura cancelada: la mano salió del encuadre. Repite la seña completa.');say('Mantén una sola mano visible durante todo el movimiento.');return;}
 const remaining=Math.max(0,Math.ceil((c.ends-now)/1000));$('trainingStatus').textContent=c.mode==='static'?`Mantén ${c.label} · ${remaining} s`:`Realiza ${c.label||'la seña'} y pulsa Terminar · máximo ${remaining} s`;
 $('stable').textContent=c.mode==='static'?'Capturando posición…':'Capturando movimiento…';
 if(now>=c.ends)finishCapture();
}
function loop(now){if(!running||!detectorActive)return;try{if(video.readyState>=2&&video.currentTime!==lastVideo&&now-lastInfer>=80){lastVideo=video.currentTime;lastInfer=now;const result=model.detectForVideo(video,now);points=result.landmarks.length===1?result.landmarks[0]:null;draw(points);
 if(capture){$('status').textContent=points?'Capturando ejemplo':'Muestra una sola mano';processCapture(now);}
 else if(!points){resetDetection();latched=null;$('status').textContent=result.landmarks.length>1?'Usa una sola mano':'Buscando mano';$('stable').textContent=result.landmarks.length>1?'Esta versión aprende señas de una mano':'Muestra una mano completa';}
 else{const r=classify(points,samples);$('status').textContent='Mano detectada';if(r.label!==candidate){candidate=r.label;since=now;ready=false;}const elapsed=now-since;ready=!!candidate&&elapsed>=800;setResult(candidate,candidate?(ready?r.source:'Mantén la posición…'):r.source);$('confirm').disabled=!ready;$('progress').style.width=(candidate?Math.min(100,elapsed/15):0)+'%';if(candidate&&latched&&candidate!==latched&&ready)latched=null;if($('auto').checked&&elapsed>=1500&&ready&&latched!==candidate)confirm();}
 }}catch(e){detectorActive=false;resetDetection();cancelCapture();alertCamera('Se detuvo el detector. El video sigue activo; pulsa Reintentar detector.');$('status').textContent='Detector detenido';console.error(e);}raf=running&&detectorActive?requestAnimationFrame(loop):null;}
function render(){$('word').replaceChildren();if(!text){const p=document.createElement('span');p.className='placeholder';p.textContent='Las palabras empiezan aquí…';$('word').append(p);}else $('word').textContent=text;$('charCount').textContent=`${text.length} / 200`;$('word').scrollTop=$('word').scrollHeight;}
function confirm(){if(!ready||!candidate||capture)return;if(practice){$('practiceFeedback').textContent=candidate===target?'¡Correcto! Prueba otra letra.':`Se detectó ${candidate}. Intenta ${target}.`;latched=candidate;return;}const add=candidate.length===1?candidate:((text&&!text.endsWith(' ')?' ':'')+candidate+' ');if(text.length+add.length>200){say('El mensaje llegó al límite de 200 caracteres.');return;}text+=add;latched=candidate;render();say('Resultado añadido. Retira la mano para repetir en modo automático.');}
function label(){return ($('customLabel').value.trim()||$('trainLetter').value).toLocaleUpperCase('es');}
function beginCapture(mode,test=false){if(!running||!detectorActive||!points){$('trainingStatus').textContent='Activa la cámara y muestra una sola mano antes de capturar.';say('Activa la cámara y muestra una mano antes de capturar.');return false;}if(capture)return false;const k=label();if(!test&&!validLabel(k)){say('Escribe una etiqueta válida de hasta 24 caracteres.');return false;}const now=performance.now();capture={mode,test,label:test?null:k,starts:now+1800,ends:now+1800+(mode==='static'?2500:12000),frames:[],misses:0};$('capture').disabled=true;$('confirm').disabled=true;$('finishCapture').disabled=mode==='static';if(test){$('settings').close();$('motionFloating').hidden=false;}return true;}
function finishCapture(){if(!capture)return;const c=capture;if(performance.now()<c.starts){say('Espera a que termine la cuenta atrás.');return;}capture=null;$('capture').disabled=false;$('finishCapture').disabled=true;$('motionFloating').hidden=true;const fs=c.frames.map(features).filter(Boolean);
 if(fs.length<12){$('trainingStatus').textContent='No hay suficientes fotogramas válidos. Repite la captura.';say('Captura demasiado corta. Mantén la mano visible al menos un segundo.');return;}
 if(c.mode==='static'){samples[c.label]=[...(samples[c.label]||[]),...fs].slice(-240);save();$('trainingStatus').textContent=`${c.label}: posición guardada. Repite con pequeñas variaciones.`;resetDetection();}
 else{const seq=sequenceFeatures(c.frames);if(!seq){say('No se pudo procesar el movimiento.');return;}if(c.test){const r=classifySequence(seq,motion);candidate=r.label;ready=!!candidate;since=performance.now();setResult(candidate,r.source);$('confirm').disabled=!ready;$('progress').style.width='0';say(r.label?`Movimiento reconocido: ${r.label}. Confirma para añadirlo.`:r.source);detectorActive=false;cancelAnimationFrame(raf);$('status').textContent='Resultado de movimiento';$('retryDetector').textContent='Continuar detección';alertCamera('El resultado queda en pantalla para que lo confirmes. Pulsa Continuar detección cuando termines.');}
 else{motion[c.label]=[...(motion[c.label]||[]),seq].slice(-20);save();$('trainingStatus').textContent=`${c.label}: movimiento guardado. Necesitas al menos 2 ejemplos; recomendamos 3 o más.`;resetDetection();}}
 counts();
}
$('start').onclick=()=>start();$('pause').onclick=()=>running?stop():start();$('confirm').onclick=confirm;$('retryDetector').onclick=()=>running?enableDetector():start();
$('switch').onclick=async()=>{try{const devices=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='videoinput');if(devices.length<2){say('Solo hay una cámara disponible.');return;}const current=stream?.getVideoTracks()[0].getSettings().deviceId;const next=devices[(devices.findIndex(d=>d.deviceId===current)+1)%devices.length];stop();await start(next.deviceId);}catch{say('No se pudo cambiar de cámara.');}};
function mirror(){video.classList.toggle('mirror',$('mirror').checked);canvas.classList.toggle('mirror',$('mirror').checked);}$('mirror').onchange=mirror;mirror();
$('erase').onclick=()=>{text=text.slice(0,-1);render();};$('space').onclick=()=>{if(text&&text.length<200&&!text.endsWith(' ')){text+=' ';render();}};$('clear').onclick=()=>{if(!text||window.confirm('¿Borrar todo el mensaje?')){text='';render();}};
$('copy').onclick=async()=>{if(!text.trim()){say('Primero construye un mensaje.');return;}try{await navigator.clipboard.writeText(text);say('Mensaje copiado.');}catch{say('No se pudo copiar. Selecciona el mensaje y cópialo manualmente.');}};
$('speak').onclick=()=>{if(!text.trim()){say('Primero construye un mensaje.');return;}if(!('speechSynthesis'in window)){say('El navegador no admite lectura en voz alta.');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang==='es-SV')||voices.find(v=>v.lang.startsWith('es'))||null;u.lang=u.voice?.lang||'es-SV';u.rate=.9;u.onerror=()=>say('No se pudo reproducir la voz. Revisa las voces disponibles.');speechSynthesis.speak(u);};
function tab(name){practice=name==='practice';$('translateView').hidden=name==='learn';$('learnView').hidden=name!=='learn';$('practiceBar').hidden=!practice;for(const b of document.querySelectorAll('[data-tab]'))b.classList.toggle('active',b.dataset.tab===name);latched=null;$('practiceFeedback').textContent='';if(name==='learn'&&running){stop();say('Cámara pausada al abrir las referencias.');}}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>tab(b.dataset.tab);
$('nextTarget').onclick=()=>{const available=[...new Set([...BASIC,...Object.keys(samples).filter(k=>k.length===1&&samples[k].length>=12)])].filter(k=>k!==target);target=available[Math.floor(Math.random()*available.length)];$('target').textContent=target;latched=null;$('practiceFeedback').textContent='';};
function settings(){counts();$('settings').showModal();}$('settingsButton').onclick=settings;$('trainShortcut').onclick=settings;
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();
for(const k of 'ABCDEFGHIJKLMNÑOPQRSTUVWXYZ'){const o=document.createElement('option');o.value=o.textContent=k;$('trainLetter').append(o);}
$('capture').onclick=()=>beginCapture($('captureMode').value);$('finishCapture').onclick=finishCapture;$('motionFloating').onclick=finishCapture;
$('settings').addEventListener('close',()=>{if(capture&&!capture.test)cancelCapture();});
$('testMotion').onclick=()=>{if(!Object.values(motion).some(v=>v.length>=2)){$('trainingStatus').textContent='Guarda primero al menos 2 movimientos de una misma seña.';return;}beginCapture('motion',true);};
$('deleteLabel').onclick=()=>{const k=label();if(window.confirm(`¿Borrar los ejemplos de ${k}?`)){if(capture)cancelCapture();delete samples[k];delete motion[k];save();counts();resetDetection();$('trainingStatus').textContent=`Ejemplos de ${k} borrados.`;}};
$('exportSamples').onclick=()=>{const blob=new Blob([JSON.stringify({version:2,language:'LESSA',samples,motion},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='senaletra-mis-ejemplos.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('importSamples').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>6*1024*1024)throw Error('El archivo supera 6 MB.');const raw=JSON.parse(await f.text());if(raw.version!==2||raw.language!=='LESSA')throw Error('Importa una exportación de SeñaLetra LESSA versión 2.');const d=cleanData(raw);if(!Object.keys(d.samples).length&&!Object.keys(d.motion).length)throw Error('No hay ejemplos válidos en este archivo.');if(!window.confirm('¿Añadir estos ejemplos? Las señas con el mismo nombre se combinarán.'))return;if(capture)cancelCapture();for(const [k,v]of Object.entries(d.samples))samples[k]=[...(samples[k]||[]),...v].slice(-240);for(const [k,v]of Object.entries(d.motion))motion[k]=[...(motion[k]||[]),...v].slice(-20);save();counts();resetDetection();$('trainingStatus').textContent='Ejemplos importados. Comprueba las señas antes de usarlas.';}catch(e){$('trainingStatus').textContent=e.message;}finally{e.target.value='';}};
window.addEventListener('pagehide',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden&&(running||loading)){stop();say('Cámara pausada al cambiar de pestaña.');}});counts();
